//Config constants
export const itemsPerPage = 50;
export const iconAssetPath = 'assets/Icons';


//STRING constants
export const KEYCODE = {
  ENTER: 13,
  UP_ARROW: 38,
  DOWN_ARROW: 40,
  TAB: 9
};

export const FILTERNAMES = {
  VERIFIED: 'VERIFIED',
  PR_POLICY: 'PR_POLICY',
  PR_DATABASE: 'PR_DATABASE',
  PR_TRANSFER_POLICY: 'PR_TRANSFER_POLICY',
  OPR_REPORTS: 'OPR_REPORTS',
  OPR_RESPONSES: 'OPR_RESPONSES',
  OPR_LETTERS: 'OPR_LETTERS',
  OPR_VERSIONS: 'OPR_VERSIONS',
  OPR_IDENTITIES_PUBLISHED: 'OPR_IDENTITIES_PUBLISHED',
  OPR_IDENTITIES_AUTHOR: 'OPR_IDENTITIES_AUTHOR',
  OPR_COMMENTS: 'OPR_COMMENTS',
  OPR_INTERACTION: 'OPR_INTERACTION',
  COREVIEW_POLICY: 'COREVIEW_POLICY',
  COREVIEW_EMAIL: 'COREVIEW_EMAIL',
  COREVIEW_FORM: 'COREVIEW_FORM',
  COREVIEW_DATABASE: 'COREVIEW_DATABASE',
  PREPRINT_POLICY: 'PREPRINT_POLICY',
  PREPRINT_VERSION: 'PREPRINT_VERSION',
  PREPRINT_CITATION: 'PREPRINT_CITATION',
  PREPRINT_MEDIA: 'PREPRINT_MEDIA',
  PREPRINT_LICENSING: 'PREPRINT_LICENSING',
  PREPRINT_SCOOP: 'PREPRINT_SCOOP',
  PREPRINT_REVIEW: 'PREPRINT_REVIEW'
};

export const JOURNAL_UID_PREFIX = 'JOURNAL-ITEM';
